recipients:
  to:
    - "Zac Walker <zwalker@ucpm.com>"
  cc: []
  bcc: []

email:
  subject_prefix: "[Forge Financials]"
  from_name: "Finance Brief Bot"
  reply_to: "zwalker@ucpm.com"

display:
  # Set to 2 or 3 — how many bullets to show per section
  per_section: 3
