rss:
  - name: Federal Reserve Press Releases
    url: https://www.federalreserve.gov/feeds/press_all.xml
  - name: FOMC Monetary Policy
    url: https://www.federalreserve.gov/feeds/press_monetary.xml
  - name: Bureau of Labor Statistics
    url: https://www.bls.gov/feeds/news.rss
  - name: Bureau of Economic Analysis
    url: https://www.bea.gov/rss.xml
  - name: Reuters Business
    url: https://feeds.reuters.com/reuters/businessNews
  - name: Financial Times World
    url: https://www.ft.com/world?format=rss
  - name: CNBC Top News
    url: https://www.cnbc.com/id/100003114/device/rss/rss.html
  - name: WSJ Markets
    url: https://feeds.a.dj.com/rss/RSSMarketsMain.xml

sec:
  current_feed: https://www.sec.gov/cgi-bin/browse-edgar?action=getcurrent&output=atom
